version: '{branch}.{build}'            # this is $(appveyor_build_version)

skip_tags: true

skip_non_tags: false

skip_branch_with_pr: false

branches:
  only:
    - vscode

skip_commits:
  files:
    - CHANGELOG.md
    - LICENSE
    - README.md
    - .gitignore
    - Pipfile.lock

image: Visual Studio 2019 

environment:
  APPVEYOR_CACHE_SKIP_RESTORE: 'false'
  APPVEYOR_CACHE_SKIP_SAVE: 'false'
  matrix:
    - PYTHON: "C:\\Python37"

matrix:
  fast_finish: true

# Set to true to skip cache restore or save
init:
  - ps: $env:PATH="$env:PYTHON;$env:PYTHON\Scripts;$env:PATH"
  - ps: echo "$env:PATH"
  - ps: echo "$env:PYTHON"
  - ps: python -V
  - ps: which python
  - ps: which pip

cache:
  - 'C:\\Python37'
  - '%USERPROFILE%\.virtualenvs'      # pipenv package installs

install:
  - ps: Set-Content -Path 'VERSION' -Value ([io.file]::ReadAllText([string](Get-Location) + '\VERSION').trim() + ".${env:APPVEYOR_BUILD_NUMBER}")
  - ps: $env:PYROCLI_VERSION = ([io.file]::ReadAllText([string](Get-Location) + '\VERSION').trim())
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade pipenv
  - which pipenv
  - pipenv update
  - pipenv install nuitka

platform: x64

configuration: Debug

build: off                          # disable Visual Studio SLN build process

build_script:
  - pipenv run python build.py --mingw64

test: off

artifacts:
  - path: '**\*.zip'

deploy:
  tag: $(PYROCLI_VERSION)
  release: 'Standalone Pyro CLI $(PYROCLI_VERSION)'
  description: >
      Standalone executable Pyro CLI version $(PYROCLI_VERSION)
      (Automated build via AppVeyor)
  provider: GitHub
  auth_token:
    secure: EhiervZBkremCKMnk/LFCC3XTbLfgu6hfWrxBIDWr9Oxf84OO4BKcH6OyH19WrBf
  artifact: /.*\.zip/
  draft: true
  prerelease: true
  on:
    branch: vscode                 # release from master branch only
    APPVEYOR_REPO_TAG: false

# Discord notification script
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL