version: '{branch}.{build}'            # this is $(appveyor_build_version)

skip_tags: false

skip_non_tags: false

skip_branch_with_pr: false

branches:
  only:
    - master

skip_commits:
  message: /^Changes:/              # Regex for matching commit message
  files:
    - CHANGELOG.md
    - LICENSE
    - README.md
    - .gitignore
    - Pipfile.lock

image: Visual Studio 2019 

environment:
  APPVEYOR_CACHE_SKIP_RESTORE: 'false'
  APPVEYOR_CACHE_SKIP_SAVE: 'false'
  matrix:
    - PYTHON: "C:\\Python37"

matrix:
  fast_finish: true

# Set to true to skip cache restore or save
init:
  - ps: $env:PATH="$env:PYTHON;$env:PYTHON\Scripts;$env:PATH"
  - ps: echo "$env:PATH"
  - ps: echo "$env:PYTHON
  - ps: python -V
  - ps: which python
  - ps: which pip

cache:
  - 'C:\\Python37'
  - '%USERPROFILE%\.virtualenvs'      # pipenv package installs

install:
  - python -m pip install --upgrade pip
  - python -m pip install pipenv
  - which pipenv
  - pipenv update
  - pipenv install nuitka

platform: Any CPU

configuration: Debug

build: off                          # disable Visual Studio SLN build process

build_script:
  - pipenv run python build.py

test: off

artifacts:
  - path: '**\*.zip'

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: 'Standalone Pyro CLI $(appveyor_repo_tag_name) ($(appveyor_build_version))'
  description: >
      Standalone executable Pyro CLI version $(appveyor_repo_tag_name)
      (Automated build via AppVeyor, $(appveyor_build_version))
      $(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)
  provider: GitHub
  auth_token:
    secure: EhiervZBkremCKMnk/LFCC3XTbLfgu6hfWrxBIDWr9Oxf84OO4BKcH6OyH19WrBf
  artifact: /.*\.zip/
  draft: true
  prerelease: true
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only

notifications:
  - provider: Webhook
    url: https://discordapp.com/api/webhooks/639029055458377729/NdAguAkN7PqBTQCmmU46XZmSe9l-vNno6aKa43MjGLlVkr-2C8YBSg_LI6s962MdsVBz
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true