version: 'build.{build}'            # this is $(appveyor_build_version)

skip_tags: false

skip_non_tags: false

skip_branch_with_pr: false

skip_commits:
  message: /-nobuild-/              # Regex for matching commit message

image: Visual Studio 2019 

environment:
  matrix:
    - PYTHON: "C:\\Python37"

build: off                          # disable Visual Studio SLN build process

matrix:
  fast_finish: true

cache:
- '%USERPROFILE%\.virtualenvs'      # pipenv package installs

install:
  - pip install pipenv
  - pipenv update
  - pipenv install nuitka

platform:
  - Any CPU

configuration: Debug

build_script:
  - pipenv run python build.py


artifacts:
  - path: '**\*.zip'

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: 'Standalone Pyro CLI $(appveyor_repo_tag_name) ($(appveyor_build_version))'
  description: >
      Standalone executable Pyro CLI version $(appveyor_repo_tag_name)
      (Automated build via AppVeyor, $(appveyor_build_version))
  provider: GitHub
  auth_token:
    secure: EhiervZBkremCKMnk/LFCC3XTbLfgu6hfWrxBIDWr9Oxf84OO4BKcH6OyH19WrBf
  artifact: /.*\.zip/
  draft: true
  prerelease: true
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only