version: '1.3.3b{build}'

skip_tags: false

skip_non_tags: true

skip_branch_with_pr: true

skip_commits:
  message: /-nobuild-/      # Regex for matching commit message

image: Visual Studio 2019 

environment:
  matrix:
    - PYTHON: "C:\\Python37"

build: off

matrix:
  fast_finish: true

# cache:

install:
  - pip install pipenv
  - pipenv install
  - pipenv install nuitka

platform:
  - Any CPU

configuration: Debug

build_script:
  - pipenv run python build.py


artifacts:
  - path: '**\*.zip'

deploy:
  release: pyro_cli-v$(appveyor_build_version)-$(appveyor_repo_tag_name)
  description: 'Automated release via AppVeyor'
  provider: GitHub
  auth_token:
    secure: EhiervZBkremCKMnk/LFCC3XTbLfgu6hfWrxBIDWr9Oxf84OO4BKcH6OyH19WrBf
  artifact: /.*\.zip/
  draft: false
  prerelease: true
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only