name: GitHub CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: dschep/install-pipenv-action@v1
    - name: Set up Python 3.7.5 (x64)
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.5
        architecture: x64
    - name: Run build script
      run: |
       pipenv shell
       pipenv install
       pipenv run build.py --mingw64
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: pyro
        path: D:\a\pyro\pyro\bin\pyro.zip
