name: GitHub CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: dschep/install-pipenv-action@v1
    - name: Set up Python 3.7.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.5
    - name: Install dependencies
      run: pipenv install --verbose
    - name: Run build script
      run: pipenv run build.py
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: pyro
        path: C:\bin\pyro.zip
